prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
    scrapeInterval: 30s
    evaluationInterval: 30s
    externalLabels:
      cluster: kind-host
  service:
    nodePort: 30090
    type: NodePort
defaultRules:
  create: false
#additionalPrometheusRulesMap:
#   - name: test-rules
#     groups:
#       - name: smo-alerts
alertmanager:
  service:
    nodePort: 30093
    type: NodePort
  config:
    global:
      resolve_timeout: 5m
    receivers:
      - name: 'webhook-receiver'
        webhook_configs:
          # Note: Replace 127.0.0.1 with the actual IP address of your SMO service
          - url: 'http://127.0.0.1:8000/alerts'
            send_resolved: false
    route:
      group_by: ['job']
      group_wait: 10s
      group_interval: 1m
      receiver: 'webhook-receiver'
      repeat_interval: 1m
      routes:
        - receiver: "webhook-receiver"
